import { NextResponse } from 'next/server';
import pool from '@/lib/db';
import { currentUser, hashPassword } from '@/lib/auth';
const forbidden = { error: 'Hanya Administrator yang memiliki akses ke modul ini.' };
async function adminOnly() { return (await currentUser())?.role === 'admin'; }
export async function GET() { if (!await currentUser()) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!await adminOnly()) return NextResponse.json(forbidden, { status: 403 }); const { rows } = await pool.query('SELECT id,name,email,role,is_active,created_at FROM users ORDER BY id'); return NextResponse.json({ users: rows }); }
export async function POST(request: Request) { if (!await currentUser()) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!await adminOnly()) return NextResponse.json(forbidden, { status: 403 }); try { const b = await request.json(); if (!b.name?.trim() || !b.email?.trim() || !b.password || !b.role) return NextResponse.json({ error: 'Nama, email, password, dan role wajib.' }, { status: 400 }); const { rows } = await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role,is_active,created_at', [b.name.trim(), b.email.trim().toLowerCase(), hashPassword(b.password), b.role]); return NextResponse.json({ user: rows[0] }, { status: 201 }); } catch { return NextResponse.json({ error: 'Email sudah terdaftar atau input tidak valid.' }, { status: 400 }); } }
export async function PUT(request: Request) { if (!await currentUser()) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!await adminOnly()) return NextResponse.json(forbidden, { status: 403 }); try { const b = await request.json(); if (!Number.isInteger(Number(b.id)) || !b.name?.trim() || !b.email?.trim() || !b.role) return NextResponse.json({ error: 'Data user tidak valid.' }, { status: 400 }); const params: unknown[] = [b.name.trim(), b.email.trim().toLowerCase(), b.role, Boolean(b.is_active), Number(b.id)]; let sql = 'UPDATE users SET name=$1,email=$2,role=$3,is_active=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$5 RETURNING id,name,email,role,is_active,created_at'; if (typeof b.password === 'string' && b.password) { params.splice(4, 0, hashPassword(b.password)); sql = 'UPDATE users SET name=$1,email=$2,role=$3,is_active=$4,password_hash=$5,updated_at=CURRENT_TIMESTAMP WHERE id=$6 RETURNING id,name,email,role,is_active,created_at'; } const { rows } = await pool.query(sql, params); return rows[0] ? NextResponse.json({ user: rows[0] }) : NextResponse.json({ error: 'User tidak ditemukan.' }, { status: 404 }); } catch { return NextResponse.json({ error: 'Email sudah terdaftar atau input tidak valid.' }, { status: 400 }); } }
export async function DELETE(request: Request) { const me = await currentUser(); if (!me) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!await adminOnly()) return NextResponse.json(forbidden, { status: 403 }); const id = Number(new URL(request.url).searchParams.get('id')); if (!Number.isInteger(id)) return NextResponse.json({ error: 'ID tidak valid.' }, { status: 400 }); if (id === me.id) return NextResponse.json({ error: 'Tidak dapat menghapus akun sendiri.' }, { status: 400 }); const result = await pool.query('DELETE FROM users WHERE id=$1', [id]); return result.rowCount ? NextResponse.json({ success: true }) : NextResponse.json({ error: 'User tidak ditemukan.' }, { status: 404 }); }
